name: Create Release
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
#  releases: write

jobs:
  release:
    runs-on: ubuntu-latest
    needs: build   # 等待所有构建 Job 完成
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Upload Release Assets - Windows
        if: exists('./artifacts/wetools-windows.zip')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/wetools-windows.zip
          asset_name: wetools-windows.zip
          asset_content_type: application/zip

      - name: Upload Release Assets - macOS
        if: exists('./artifacts/wetools-macos.zip')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/wetools-macos.zip
          asset_name: wetools-macos.zip
          asset_content_type: application/zip

      - name: Upload Release Assets - Linux
        if: exists('./artifacts/wetools-linux.tar.gz')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/wetools-linux.tar.gz
          asset_name: wetools-linux.tar.gz
          asset_content_type: application/gzip
