name: Build And Release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
        include:
          - os: windows-latest
            output-name: wetools-windows.zip
            build-command: flutter build windows
            artifact-path: build/windows/x64/runner/Release
          - os: macos-latest
            output-name: wetools-macos.zip
            build-command: flutter build macos
            artifact-path: build/macos/Build/Products/Release/wetools.app
          - os: ubuntu-latest
            output-name: wetools-linux.tar.gz
            build-command: flutter build linux
            artifact-path: build/linux/x64/release/bundle
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: 'stable'

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Get dependencies
        run: flutter pub get

      - name: Build application
        run: |
          flutter config --enable-windows-desktop
          flutter config --enable-macos-desktop
          flutter config --enable-linux-desktop
          ${{ matrix.build-command }}

      - name: Create archive
        run: |
          cd ${{ matrix.artifact-path }}
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            7z a ../../../${{ matrix.output-name }} .
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            zip -r ../../../${{ matrix.output-name }} .
          else
            tar czf ../../../${{ matrix.output-name }} .
          fi
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output-name }}
          path: ${{ matrix.output-name }}

  release:
    runs-on: ubuntu-latest
    needs: build    # 等待所有构建 Job 完成
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Check if Windows artifact exists
        id: check_windows_artifact
        run: |
          if [ -f ./artifacts/wetools-windows.zip ]; then
            echo "windows_artifact_exists=true" >> $GITHUB_OUTPUT
          else
            echo "windows_artifact_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Check if macOS artifact exists
        id: check_macos_artifact
        run: |
          if [ -f ./artifacts/wetools-macos.zip ]; then
            echo "macos_artifact_exists=true" >> $GITHUB_OUTPUT
          else
            echo "macos_artifact_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Check if Linux artifact exists
        id: check_linux_artifact
        run: |
          if [ -f ./artifacts/wetools-linux.tar.gz ]; then
            echo "linux_artifact_exists=true" >> $GITHUB_OUTPUT
          else
            echo "linux_artifact_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Upload Release Assets - Windows
        if: steps.check_windows_artifact.outputs.windows_artifact_exists == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/wetools-windows.zip
          asset_name: wetools-windows.zip
          asset_content_type: application/zip

      - name: Upload Release Assets - macOS
        if: steps.check_macos_artifact.outputs.macos_artifact_exists == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/wetools-macos.zip
          asset_name: wetools-macos.zip
          asset_content_type: application/zip

      - name: Upload Release Assets - Linux
        if: steps.check_linux_artifact.outputs.linux_artifact_exists == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/wetools-linux.tar.gz
          asset_name: wetools-linux.tar.gz
          asset_content_type: application/gzip